import { useState, useEffect } from 'react';
import type { FeedItem, TickerItem } from '../types';

// TODO: remplacer par Firestore
const TICKER_ITEMS: TickerItem[] = [
  { id: 't1', text: "⚽ 78' — Bersot double la mise pour Annecy FC", urgent: true },
  { id: 't2', text: '📅 Report : Veyrier Utd vs Poisy Stars → Mer. 22 Jan', urgent: false },
  { id: 't3', text: '🏆 Meythet FC 0–3 Cran Giants · FT', urgent: false },
  { id: 't4', text: '⚡ Quarts de finale Summer Cup S3 : programme confirmé', urgent: false },
];

// TODO: remplacer par Firestore
const FEED_ITEMS: FeedItem[] = [
  { id: 'f1', type: 'hero', category: 'official', title: 'Annecy FC en route vers la finale — une saison historique', excerpt: "Après 14 victoires en 18 matchs, le club des Marquisats s'impose comme favori incontesté de la Summer Cup S3. Retour sur un parcours hors norme.", img: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=800&q=80', timeLabel: 'Il y a 1 h', timeGroup: 'today', pinned: true, breaking: true, author: { name: 'Rédaction Tcheksplay', role: 'Média Officiel', verified: true, avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=80&h=80' }, reactions: { fire: 142, clap: 87, heart: 63, wow: 29 }, comments: [{ id: 'c1', author: 'Yassin M.', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=80&h=80', text: 'Saison de ouf 🔥 Killian est au dessus de tout le monde', time: 'Il y a 45 min', likes: 12 }, { id: 'c2', author: 'Théo G.', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=80&h=80', text: 'Respect au coach, système tactique impeccable', time: 'Il y a 1 h', likes: 8 }], totalComments: 34, tag: 'À La Une', tagColor: '#B7FF1A' },
  { id: 'f2', type: 'result', category: 'results', title: "Victoire éclatante d'Annecy FC sur Seynod City", excerpt: 'Un match dominé de bout en bout. Bersot et Mebrouk ont illuminé le terrain des Marquisats.', img: 'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?auto=format&fit=crop&w=800&q=80', timeLabel: 'Il y a 3 h', timeGroup: 'today', author: { name: 'Stats Tcheksplay', role: 'Bureau Sportif', verified: true, avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=80&h=80' }, reactions: { fire: 98, clap: 54, heart: 41, wow: 17 }, comments: [{ id: 'c3', author: 'Lucas P.', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=80&h=80', text: "Score mérité. On savait qu'AFC était au niveau 💪", time: 'Il y a 2 h', likes: 6 }], totalComments: 19, tag: 'Résultat · FT', tagColor: '#2E8F57', matchData: { home: 'Annecy FC', away: 'Seynod City', homeScore: 2, awayScore: 1, venue: 'Terrain des Marquisats' } },
  { id: 'f3', type: 'announcement', category: 'official', title: 'Nouvelles règles arbitrage — en vigueur dès la J19', excerpt: 'La commission sportive Tcheksplay a validé 3 ajustements au règlement. Consultez le document officiel.', img: 'https://images.unsplash.com/photo-1551958219-acbc595d4c80?auto=format&fit=crop&w=800&q=80', timeLabel: 'Il y a 5 h', timeGroup: 'today', author: { name: 'Commission Sportive', role: 'Officiel', verified: true, avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=80&h=80' }, reactions: { fire: 24, clap: 61, heart: 18, wow: 45 }, comments: [], totalComments: 8, tag: 'Annonce', tagColor: '#7BA7D9' },
  { id: 'f4', type: 'schedule_change', category: 'schedule', title: 'Report du match Veyrier Utd vs Poisy Stars', excerpt: 'Suite aux intempéries, la rencontre est déplacée au mercredi 22 janvier.', img: 'https://images.unsplash.com/photo-1517927033932-b3d18e61fb3a?auto=format&fit=crop&w=800&q=80', timeLabel: 'Il y a 6 h', timeGroup: 'today', author: { name: 'Direction Compétition', role: 'Officiel', verified: true, avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=80&h=80' }, reactions: { fire: 5, clap: 12, heart: 4, wow: 31 }, comments: [], totalComments: 11, tag: 'Calendrier', tagColor: '#C9C1A2', scheduleData: { match: 'Veyrier Utd vs Poisy Stars', oldDate: 'Lun. 20 Jan · 20h30', newDate: 'Mer. 22 Jan · 20h30', reason: 'Conditions météo défavorables' } },
  { id: 'f5', type: 'team_photo', category: 'media', title: "Dans les vestiaires d'Annecy FC — les photos exclusives", excerpt: "Notre photographe était présent avant le coup d'envoi. 18 clichés inédits à découvrir.", img: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=800&q=80', timeLabel: 'Hier · 18h', timeGroup: 'yesterday', author: { name: 'Studio Tcheks', role: 'Photo & Vidéo', verified: true, avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=80&h=80' }, reactions: { fire: 76, clap: 112, heart: 94, wow: 38 }, comments: [{ id: 'c4', author: 'Amine T.', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf45f1d?auto=format&fit=crop&w=80&h=80', text: 'Les photos sont vraiment de qualité 📸', time: 'Hier', likes: 14 }], totalComments: 22, tag: '18 Photos', tagColor: '#C9C1A2' },
  { id: 'f6', type: 'interview', category: 'official', title: '"On joue pour le quartier, pas pour les stats" — Killian Bersot', excerpt: "Le meilleur buteur de la saison S3 se confie sur sa progression, son équipe et ses ambitions.", img: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80', timeLabel: 'Hier · 14h', timeGroup: 'yesterday', author: { name: 'Rédaction Tcheksplay', role: 'Interview', verified: true, avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=80&h=80' }, reactions: { fire: 201, clap: 88, heart: 147, wow: 52 }, comments: [{ id: 'c5', author: 'Yassin M.', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=80&h=80', text: "Killian est trop humble. C'est un vrai chef 🐐", time: 'Hier', likes: 23 }, { id: 'c6', author: 'Lucas P.', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=80&h=80', text: 'Interview motivante, respect', time: 'Hier', likes: 9 }], totalComments: 47, tag: 'Interview', tagColor: '#C9C1A2' },
  { id: 'f7', type: 'reward', category: 'rewards', title: 'Killian Bersot sacré MVP de la Journée 18', excerpt: "Avec son doublé décisif, le numéro 9 d'Annecy FC remporte le titre de meilleur joueur.", img: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=80&h=80', timeLabel: 'Il y a 2 j.', timeGroup: 'older', author: { name: 'Tcheksplay Awards', role: 'Récompenses', verified: true, avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=80&h=80' }, reactions: { fire: 183, clap: 125, heart: 96, wow: 44 }, comments: [], totalComments: 29, tag: 'Récompense', tagColor: '#F4C542', rewardData: { player: 'Killian Bersot', award: 'MVP Journée 18', team: 'Annecy FC', img: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=80&h=80' } },
  { id: 'f8', type: 'solidarity', category: 'solidarity', title: 'Rénovation Playground Marquisats — 85 % atteint !', excerpt: 'Grâce à la communauté Tcheksplay, le projet avance à grande vitesse. Merci aux 124 donateurs.', img: 'https://images.unsplash.com/photo-1553778263-73a83bab9b0c?auto=format&fit=crop&w=800&q=80', timeLabel: 'Il y a 2 j.', timeGroup: 'older', author: { name: 'Tcheks Impact', role: 'Initiative Solidaire', verified: true, avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=80&h=80' }, reactions: { fire: 67, clap: 201, heart: 178, wow: 34 }, comments: [], totalComments: 16, tag: 'Solidarité', tagColor: '#2E8F57', solidarityData: { project: 'Playground Marquisats', raised: 8500, goal: 10000, donors: 124 } },
  { id: 'f9', type: 'tournament', category: 'official', title: 'Programme officiel des quarts de finale — Summer Cup S3', excerpt: '4 affiches de rêve. Les dates, lieux et horaires confirmés par la direction.', img: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=800&q=80', timeLabel: 'Il y a 3 j.', timeGroup: 'older', author: { name: 'Direction Compétition', role: 'Officiel', verified: true, avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=80&h=80' }, reactions: { fire: 89, clap: 76, heart: 43, wow: 21 }, comments: [], totalComments: 13, tag: 'Tournoi', tagColor: '#B7FF1A' },
  { id: 'f10', type: 'sponsored', category: 'sponsored', title: 'Nike Football × Tcheksplay — La nouvelle collection arrive', excerpt: 'Découvrez les équipements officiels de la saison S3. Commandez avec votre réduction exclusive.', img: 'https://images.unsplash.com/photo-1517927033932-b3d18e61fb3a?auto=format&fit=crop&w=800&q=80', timeLabel: 'Il y a 4 j.', timeGroup: 'older', sponsored: true, sponsoredBy: 'Nike', author: { name: 'Nike Football', role: 'Partenaire Officiel', verified: false, avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=80&h=80' }, reactions: { fire: 34, clap: 28, heart: 19, wow: 11 }, comments: [], totalComments: 4, tag: 'Partenaire · Nike', tagColor: '#8A938C' },
];

interface FeedData {
  items: FeedItem[];
  tickerItems: TickerItem[];
  loading: boolean;
}

export function useFeedData(): FeedData {
  const [loading, setLoading] = useState(true);

  // TODO: remplacer par Firestore — simuler un délai réseau
  useEffect(() => {
    const timer = setTimeout(() => setLoading(false), 350);
    return () => clearTimeout(timer);
  }, []);

  return { items: FEED_ITEMS, tickerItems: TICKER_ITEMS, loading };
}
